### ISSUE TITLE
execution stuck

### ISSUE THREAD

**Issue by delanym** [tomasbjerre/git-changelog-lib#95]
Hi. I tried this basic config on my project. 

        <plugin>
          <groupId>se.bjurr.gitchangelog</groupId>
          <artifactId>git-changelog-maven-plugin</artifactId>
          <version>1.64</version>
          <executions>
            <execution>
              <id>GenerateGitChangelog</id>
              <phase>generate-sources</phase>
              <goals>
                <goal>git-changelog</goal>
              </goals>
              <configuration>
                <templateContent>
                  <![CDATA[
    # Changelog
    Changelog of My Project.
                  ]]>
                </templateContent>
                <skip>false</skip>
              </configuration>
            </execution>
          </executions>
        </plugin>

When I run `mvn clean install -e -X` the output goes on ad infinitum.

```
...
[main] [DEBUG] Work left: 12892
[main] [DEBUG] Work left: 13001
[main] [DEBUG] Work left: 13106
[main] [DEBUG] Work left: 13226
[main] [DEBUG] Work left: 13323
[main] [DEBUG] Work left: 13401
[main] [DEBUG] Work left: 13480
[main] [DEBUG] Work left: 13790
[main] [DEBUG] Work left: 13763
[main] [DEBUG] Work left: 13830
[main] [DEBUG] Work left: 13901
[main] [DEBUG] Work left: 13986
...
```

**Comment by JohT** [comment]
### Reproduce
If it's of any help: It seems that I have the same issue. It should theoretically be reproducible:
- Clone https://github.com/JohT/showcase-quarkus-eventsourcing.git 
- Execute `mvn compile`

This leads to 
```
[DEBUG] Configuring mojo se.bjurr.gitchangelog:git-changelog-maven-plugin:1.96.0:git-changelog from plugin realm ClassRealm[plugin>se.bjurr.gitchangelog:git-changelog-maven-plugin:1.96.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7]
[DEBUG] Configuring mojo 'se.bjurr.gitchangelog:git-changelog-maven-plugin:1.96.0:git-changelog' with basic configurator -->
[DEBUG]   (f) customIssues = []
[DEBUG]   (f) extendedHeaders = {}
[DEBUG]   (f) extendedVariables = {}
[DEBUG]   (f) extendedVariablesCli = []
[DEBUG]   (f) templateFile = changelogTemplate.mustache
[DEBUG]   (f) untaggedName = Next Release
[DEBUG] -- end configuration --
[INFO] Extended variables:
[INFO] No output set, using file CHANGELOG.md
[DEBUG] About to parse: inline@7e3fb4f4
[DEBUG] Building AST
[DEBUG] Applying Mustache spec
[DEBUG] Creating templates
[DEBUG] file=/Users/.....<here are some files>
...
[DEBUG] file=/Users/joht/Repositories/git/showcase-quarkus-eventsourcing/.git/packed-refs, isRacyClean=false, read=2023-03-11 20:18:50.323458000, lastModified=2023-03-11 12:11:33.694667369, delta=29236628790631 ns, racy<=5000 ns
[DEBUG] file=/Users/joht/Repositories/git/showcase-quarkus-eventsourcing/.git/packed-refs, is unmodified
[DEBUG] Work left: 2
[DEBUG] Work left: 2
[DEBUG] Work left: 2
[DEBUG] Work left: 2
[DEBUG] Work left: 2
[DEBUG] Work left: 2
[DEBUG] Work left: 3
...
```

### Workaround

Starting it with `mvn changelog:changelog` seems to work without any issues. If I use `<skip>true</skip>` within the configuration of the plugin it won't run during build anymore. So I can start both commands separately. Nevertheless this is not ideal. 

Here is the output of this for comparison. There is much more going on within the configuration:

```
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-changelog-plugin:2.3:changelog' with basic configurator -->
[DEBUG]   (f) basedir = /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing
[DEBUG]   (f) connectionType = connection
[DEBUG]   (f) dateFormat = yyyy-MM-dd HH:mm:ss
[DEBUG]   (f) developers = []
[DEBUG]   (f) displayFileDetailUrl = https://github.com/JohT/showcase-quarkus-eventsourcing
[DEBUG]   (f) encodeFileUri = false
[DEBUG]   (f) headingDateFormat = yyyy-MM-dd
[DEBUG]   (f) issueIDRegexPattern = [a-zA-Z]{2,}-\d+
[DEBUG]   (f) issueLinkUrl = http://jira.codehaus.org/browse/%ISSUE%
[DEBUG]   (f) offline = false
[DEBUG]   (f) outputDirectory = /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing/target/site
[DEBUG]   (f) outputEncoding = UTF-8
[DEBUG]   (f) outputXML = /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing/target/changelog.xml
[DEBUG]   (f) outputXMLExpiration = 60
[DEBUG]   (f) range = -1
[DEBUG]   (f) scmUrl = https://github.com/JohT/showcase-quarkus-eventsourcing
[DEBUG]   (f) skip = false
[DEBUG]   (f) type = range
[DEBUG]   (f) project = MavenProject: io.github.joht.showcase.quarkuseventsourcing:showcase-quarkus-eventsourcing:2.0.1-SNAPSHOT @ /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing/pom.xml
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@14c93774
[DEBUG] -- end configuration --
[INFO] Generating changed sets xml to: /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing/target/changelog.xml
[INFO] Executing: /bin/sh -c cd /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing && git whatchanged '--since=2023-02-09 19:30:26 +0000' '--until=2023-03-12 19:30:26 +0000' --date=iso -- /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing
[INFO] Working directory: /Users/joht/Repositories/git/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing
```

**Comment by tomasbjerre** [comment]
Thanks @JohT ! This algorithm is a mess... but I think I fixed it.

I was able to generate your changelog with:

```sh
npx git-changelog-command-line -t showcase-quarkus-eventsourcing/changelogTemplate.mustache -ut "Next Release" -of showcase-quarkus-eventsourcing/CHANGELOG.md
```

**Comment by JohT** [comment]
@tomasbjerre thank you so much for your time.

How can I "translate" the node command to maven? I was able to generate the changeling with `mvn changelog:changelog` (see my Workaround). I'm not sure why this works and what the difference is between running one plugin on its own (working) and running the whole build (not working).

If this is currently the way to do it, then I'll be fine with it.

**Comment by tomasbjerre** [comment]
I guess Maven does not pick up same configuration with those two commands, I don't know.

I found the issue while debugging a test case in this library where I point at your repository.

**Comment by JohT** [comment]
@tomasbjerre, the problem is solved at least on my side as far as I can see for now with [Update dependency se.bjurr.gitchangelog:git-changelog-maven-plugin to v1.96.1](https://github.com/JohT/showcase-quarkus-eventsourcing/pull/161). 🎉 Thank you very much. Well done.👏

**Comment by delanym** [comment]
@JohT use pluginManagement to configure the plugin without necessarily executing it (no need to skip)

@tomasbjerre I don't know what's changed, but the behaviour since 1.64 is still the same: out of lifecycle execution completes, while binding the execution to a phase in the default lifecycle gets stuck.

If changelog:changelog is going to be the only way, then the docs at [git-changelog-maven-plugin](https://github.com/tomasbjerre/git-changelog-maven-plugin) need attention. Someone new is not going to find this ticket.

You might have luck bringing this issue up at [dev@maven.apache.org](mailto:dev@maven.apache.org)

**Comment by tomasbjerre** [comment]
@delanym in the case of @JohT there was a logical bug in this library that actually resulted in infinite bug. Your comment sounds like there is also a bug with Maven. I would happily investigate that, but I would need a repository to reproduce it.

**Comment by delanym** [comment]
@JohT I failed to build your showcase-quarkus-eventsourcing repo. Do you still need to run changelog:changelog outside the default lifecycle?

**Comment by JohT** [comment]
@delanym i probably should have mentioned that you need to change into the project directory showcase... if you are in Repository root.

Also I need to mention that my master branch works now with the new version. So you might change the version number of the changelog plugin as well if you did the clone recently.

**Comment by delanym** [comment]
@JohT the jasmine-maven-plugin is failing with
```
Auto configuration failed                           
140627168524224:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140627168524224:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140627168524224:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
140627168524224:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers
```
which looks like a platform issue. But then I noticed your Maven Wrapper was only added with a Windows startup script. I'm building on Linux.

@tomasbjerre JohT's repo is my best hope at the moment for a reproducer

**Comment by JohT** [comment]
@delanym, my pipeline (GitHub Actions) runs on Ubuntu (22.04.2) with Open Adapt Java 17 https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jdk_x64_linux_hotspot_17.0.6_10.tar.gz. It also works on Linux. I don't know how the container is configured in detail though.

Here is my GitHub Actions Configuration:
https://github.com/JohT/showcase-quarkus-eventsourcing/blob/master/.github/workflows/maven.yml

**Comment by tomasbjerre** [comment]
Perhaps you can add a Maven Wrapper with intended version. I did `mvn wrapper:wrapper -Dmaven=3.9.1`.

I tested with:

```
15:03 $ ./mvnw -version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /home/bjerre/.m2/wrapper/dists/apache-maven-3.9.1-bin/2cpar40ui5s2pm3ja4s69ub7fa/apache-maven-3.9.1
Java version: 1.8.0_362, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: sv_SE, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-70-generic", arch: "amd64", family: "unix"
```

And I am getting:

```
15:03 $ ./mvnw -B package --file pom.xml
[INFO] Scanning for projects...
[INFO] 
[INFO] --< io.github.joht.showcase.quarkuseventsourcing:showcase-quarkus-eventsourcing >--
[INFO] Building showcase-quarkus-eventsourcing 2.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Artifact org.apache.maven.plugins:maven-resources-plugin:pom:3.3.0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.3.0/maven-resources-plugin-3.3.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.3.0/maven-resources-plugin-3.3.0.pom (0 B at 0 B/s)
[INFO] Artifact org.apache.maven.plugins:maven-resources-plugin:jar:3.3.0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.3.0/maven-resources-plugin-3.3.0.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.3.0/maven-resources-plugin-3.3.0.jar (0 B at 0 B/s)
[INFO] Artifact org.apache.maven.plugins:maven-jar-plugin:pom:3.3.0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.3.0/maven-jar-plugin-3.3.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.3.0/maven-jar-plugin-3.3.0.pom (0 B at 0 B/s)
[INFO] Artifact org.apache.maven.plugins:maven-jar-plugin:jar:3.3.0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases)]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.3.0/maven-jar-plugin-3.3.0.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.3.0/maven-jar-plugin-3.3.0.jar (0 B at 0 B/s)
[INFO] 
[INFO] --- jacoco:0.8.9:prepare-agent (default-prepare-agent) @ showcase-quarkus-eventsourcing ---
[INFO] argLine set to -javaagent:/home/bjerre/.m2/repository/org/jacoco/org.jacoco.agent/0.8.9/org.jacoco.agent-0.8.9-runtime.jar=destfile=/home/bjerre/workspace/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing/target/jacoco-quarkus.exec,append=true,exclclassloader=*QuarkusClassLoader
[INFO] 
[INFO] --- git-changelog-maven-plugin:1.96.1:git-changelog (GenerateGitChangelog) @ showcase-quarkus-eventsourcing ---
[INFO] Extended variables:
[INFO] No output set, using file CHANGELOG.md
[INFO] #
[INFO] # Wrote: CHANGELOG.md
[INFO] #
[INFO] 
[INFO] --- resources:3.3.0:resources (default-resources) @ showcase-quarkus-eventsourcing ---
[INFO] Artifact org.apache.maven.shared:maven-filtering:pom:3.3.0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases), apache.snapshots (https://repository.apache.org/snapshots, default, snapshots)]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-filtering/3.3.0/maven-filtering-3.3.0.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-filtering/3.3.0/maven-filtering-3.3.0.pom (0 B at 0 B/s)
[INFO] Artifact org.apache.maven.shared:maven-filtering:jar:3.3.0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo.maven.apache.org/maven2, default, releases), apache.snapshots (https://repository.apache.org/snapshots, default, snapshots)]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-filtering/3.3.0/maven-filtering-3.3.0.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-filtering/3.3.0/maven-filtering-3.3.0.jar (0 B at 0 B/s)
[INFO] Copying 28 resources
[INFO] 
[INFO] --- yuicompressor:1.5.1:compress (default) @ showcase-quarkus-eventsourcing ---
[INFO] generate aggregation : /home/bjerre/workspace/showcase-quarkus-eventsourcing/showcase-quarkus-eventsourcing/target/aggregated/javascript/application.js
[INFO] application.js (44715b)
[INFO] application.js (44715b) -> application.js (36089b)[80%]
[INFO] total input (44715b) -> output (36089b)[80%]
[INFO] nb warnings: 0, nb errors: 0
[INFO] 
[INFO] --- quarkus:3.0.0.Final:generate-code (default) @ showcase-quarkus-eventsourcing ---
[WARNING] Error injecting: io.quarkus.maven.GenerateCodeMojo
java.lang.TypeNotPresentException: Type io.quarkus.maven.GenerateCodeMojo not present
    at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:147)
    at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:86)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:67)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:109)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:124)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:62)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1101)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:486)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:114)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:827)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:272)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:195)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:47)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:156)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:72)
Caused by: java.lang.UnsupportedClassVersionError: io/quarkus/maven/GenerateCodeMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1 (Native Method)
    at java.lang.ClassLoader.defineClass (ClassLoader.java:756)
    at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass (URLClassLoader.java:473)
    at java.net.URLClassLoader.access$100 (URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged (Native Method)
    at java.net.URLClassLoader.findClass (URLClassLoader.java:362)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf (ClassRealm.java:425)
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:42)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:139)
    at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:86)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:67)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:109)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:124)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:62)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1101)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:486)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:114)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:827)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:272)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:195)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:47)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:156)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:72)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.330 s
[INFO] Finished at: 2023-04-22T15:03:50+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.Final:generate-code (default) on project showcase-quarkus-eventsourcing: Execution default of goal io.quarkus:quarkus-maven-plugin:3.0.0.Final:generate-code failed: Unable to load the mojo 'generate-code' in the plugin 'io.quarkus:quarkus-maven-plugin:3.0.0.Final' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: io/quarkus/maven/GenerateCodeMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>io.quarkus:quarkus-maven-plugin:3.0.0.Final
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-maven-plugin/3.0.0.Final/quarkus-maven-plugin-3.0.0.Final.jar
[ERROR] urls[1] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-bootstrap-core/3.0.0.Final/quarkus-bootstrap-core-3.0.0.Final.jar
[ERROR] urls[2] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-bootstrap-app-model/3.0.0.Final/quarkus-bootstrap-app-model-3.0.0.Final.jar
[ERROR] urls[3] = file:/home/bjerre/.m2/repository/org/jboss/logging/commons-logging-jboss-logging/1.0.0.Final/commons-logging-jboss-logging-1.0.0.Final.jar
[ERROR] urls[4] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-io/2.1.0/smallrye-common-io-2.1.0.jar
[ERROR] urls[5] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-bootstrap-maven-resolver/3.0.0.Final/quarkus-bootstrap-maven-resolver-3.0.0.Final.jar
[ERROR] urls[6] = file:/home/bjerre/.m2/repository/io/smallrye/beanbag/smallrye-beanbag-maven/1.1.0/smallrye-beanbag-maven-1.1.0.jar
[ERROR] urls[7] = file:/home/bjerre/.m2/repository/io/smallrye/beanbag/smallrye-beanbag-sisu/1.1.0/smallrye-beanbag-sisu-1.1.0.jar
[ERROR] urls[8] = file:/home/bjerre/.m2/repository/io/smallrye/beanbag/smallrye-beanbag/1.1.0/smallrye-beanbag-1.1.0.jar
[ERROR] urls[9] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-constraint/2.1.0/smallrye-common-constraint-2.1.0.jar
[ERROR] urls[10] = file:/home/bjerre/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
[ERROR] urls[11] = file:/home/bjerre/.m2/repository/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
[ERROR] urls[12] = file:/home/bjerre/.m2/repository/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
[ERROR] urls[13] = file:/home/bjerre/.m2/repository/org/apache/maven/maven-builder-support/3.9.1/maven-builder-support-3.9.1.jar
[ERROR] urls[14] = file:/home/bjerre/.m2/repository/org/apache/maven/resolver/maven-resolver-named-locks/1.9.7/maven-resolver-named-locks-1.9.7.jar
[ERROR] urls[15] = file:/home/bjerre/.m2/repository/org/apache/maven/wagon/wagon-http-lightweight/3.5.3/wagon-http-lightweight-3.5.3.jar
[ERROR] urls[16] = file:/home/bjerre/.m2/repository/org/apache/maven/wagon/wagon-http-shared/3.5.3/wagon-http-shared-3.5.3.jar
[ERROR] urls[17] = file:/home/bjerre/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar
[ERROR] urls[18] = file:/home/bjerre/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
[ERROR] urls[19] = file:/home/bjerre/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[20] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-fs-util/0.0.9/quarkus-fs-util-0.0.9.jar
[ERROR] urls[21] = file:/home/bjerre/.m2/repository/org/jboss/logmanager/jboss-logmanager-embedded/1.1.1/jboss-logmanager-embedded-1.1.1.jar
[ERROR] urls[22] = file:/home/bjerre/.m2/repository/org/jboss/logging/jboss-logging/3.5.0.Final/jboss-logging-3.5.0.Final.jar
[ERROR] urls[23] = file:/home/bjerre/.m2/repository/org/apache/maven/maven-embedder/3.9.1/maven-embedder-3.9.1.jar
[ERROR] urls[24] = file:/home/bjerre/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
[ERROR] urls[25] = file:/home/bjerre/.m2/repository/com/google/inject/guice/5.1.0/guice-5.1.0.jar
[ERROR] urls[26] = file:/home/bjerre/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[27] = file:/home/bjerre/.m2/repository/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
[ERROR] urls[28] = file:/home/bjerre/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[ERROR] urls[29] = file:/home/bjerre/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar
[ERROR] urls[30] = file:/home/bjerre/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar
[ERROR] urls[31] = file:/home/bjerre/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
[ERROR] urls[32] = file:/home/bjerre/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-wagon/1.9.7/maven-resolver-transport-wagon-1.9.7.jar
[ERROR] urls[33] = file:/home/bjerre/.m2/repository/org/apache/maven/wagon/wagon-http/3.5.3/wagon-http-3.5.3.jar
[ERROR] urls[34] = file:/home/bjerre/.m2/repository/org/apache/maven/wagon/wagon-file/3.5.3/wagon-file-3.5.3.jar
[ERROR] urls[35] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-core-deployment/3.0.0.Final/quarkus-core-deployment-3.0.0.Final.jar
[ERROR] urls[36] = file:/home/bjerre/.m2/repository/org/aesh/readline/2.4/readline-2.4.jar
[ERROR] urls[37] = file:/home/bjerre/.m2/repository/org/aesh/aesh/2.7/aesh-2.7.jar
[ERROR] urls[38] = file:/home/bjerre/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[ERROR] urls[39] = file:/home/bjerre/.m2/repository/org/wildfly/common/wildfly-common/1.5.4.Final-format-001/wildfly-common-1.5.4.Final-format-001.jar
[ERROR] urls[40] = file:/home/bjerre/.m2/repository/io/quarkus/gizmo/gizmo/1.6.0.Final/gizmo-1.6.0.Final.jar
[ERROR] urls[41] = file:/home/bjerre/.m2/repository/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
[ERROR] urls[42] = file:/home/bjerre/.m2/repository/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
[ERROR] urls[43] = file:/home/bjerre/.m2/repository/io/smallrye/jandex/3.0.5/jandex-3.0.5.jar
[ERROR] urls[44] = file:/home/bjerre/.m2/repository/org/ow2/asm/asm/9.5/asm-9.5.jar
[ERROR] urls[45] = file:/home/bjerre/.m2/repository/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
[ERROR] urls[46] = file:/home/bjerre/.m2/repository/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
[ERROR] urls[47] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-development-mode-spi/3.0.0.Final/quarkus-development-mode-spi-3.0.0.Final.jar
[ERROR] urls[48] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-class-change-agent/3.0.0.Final/quarkus-class-change-agent-3.0.0.Final.jar
[ERROR] urls[49] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-devtools-utilities/3.0.0.Final/quarkus-devtools-utilities-3.0.0.Final.jar
[ERROR] urls[50] = file:/home/bjerre/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar
[ERROR] urls[51] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-core/3.0.0.Final/quarkus-core-3.0.0.Final.jar
[ERROR] urls[52] = file:/home/bjerre/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar
[ERROR] urls[53] = file:/home/bjerre/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar
[ERROR] urls[54] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-os/2.1.0/smallrye-common-os-2.1.0.jar
[ERROR] urls[55] = file:/home/bjerre/.m2/repository/io/smallrye/config/smallrye-config/3.2.1/smallrye-config-3.2.1.jar
[ERROR] urls[56] = file:/home/bjerre/.m2/repository/io/smallrye/config/smallrye-config-core/3.2.1/smallrye-config-core-3.2.1.jar
[ERROR] urls[57] = file:/home/bjerre/.m2/repository/org/eclipse/microprofile/config/microprofile-config-api/3.0.2/microprofile-config-api-3.0.2.jar
[ERROR] urls[58] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-annotation/2.1.0/smallrye-common-annotation-2.1.0.jar
[ERROR] urls[59] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-expression/2.1.0/smallrye-common-expression-2.1.0.jar
[ERROR] urls[60] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-function/2.1.0/smallrye-common-function-2.1.0.jar
[ERROR] urls[61] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-classloader/2.1.0/smallrye-common-classloader-2.1.0.jar
[ERROR] urls[62] = file:/home/bjerre/.m2/repository/io/smallrye/config/smallrye-config-common/3.2.1/smallrye-config-common-3.2.1.jar
[ERROR] urls[63] = file:/home/bjerre/.m2/repository/org/jboss/logging/jboss-logging-annotations/2.2.1.Final/jboss-logging-annotations-2.2.1.Final.jar
[ERROR] urls[64] = file:/home/bjerre/.m2/repository/org/jboss/threads/jboss-threads/3.5.0.Final/jboss-threads-3.5.0.Final.jar
[ERROR] urls[65] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-bootstrap-runner/3.0.0.Final/quarkus-bootstrap-runner-3.0.0.Final.jar
[ERROR] urls[66] = file:/home/bjerre/.m2/repository/io/github/crac/org-crac/0.1.3/org-crac-0.1.3.jar
[ERROR] urls[67] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-builder/3.0.0.Final/quarkus-builder-3.0.0.Final.jar
[ERROR] urls[68] = file:/home/bjerre/.m2/repository/org/graalvm/sdk/graal-sdk/22.3.0/graal-sdk-22.3.0.jar
[ERROR] urls[69] = file:/home/bjerre/.m2/repository/org/junit/platform/junit-platform-launcher/1.9.2/junit-platform-launcher-1.9.2.jar
[ERROR] urls[70] = file:/home/bjerre/.m2/repository/org/junit/platform/junit-platform-engine/1.9.2/junit-platform-engine-1.9.2.jar
[ERROR] urls[71] = file:/home/bjerre/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar
[ERROR] urls[72] = file:/home/bjerre/.m2/repository/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar
[ERROR] urls[73] = file:/home/bjerre/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar
[ERROR] urls[74] = file:/home/bjerre/.m2/repository/org/junit/jupiter/junit-jupiter/5.9.2/junit-jupiter-5.9.2.jar
[ERROR] urls[75] = file:/home/bjerre/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar
[ERROR] urls[76] = file:/home/bjerre/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.9.2/junit-jupiter-params-5.9.2.jar
[ERROR] urls[77] = file:/home/bjerre/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar
[ERROR] urls[78] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-project-core-extension-codestarts/3.0.0.Final/quarkus-project-core-extension-codestarts-3.0.0.Final.jar
[ERROR] urls[79] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-devtools-common/3.0.0.Final/quarkus-devtools-common-3.0.0.Final.jar
[ERROR] urls[80] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-devtools-registry-client/3.0.0.Final/quarkus-devtools-registry-client-3.0.0.Final.jar
[ERROR] urls[81] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-devtools-message-writer/3.0.0.Final/quarkus-devtools-message-writer-3.0.0.Final.jar
[ERROR] urls[82] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-devtools-base-codestarts/3.0.0.Final/quarkus-devtools-base-codestarts-3.0.0.Final.jar
[ERROR] urls[83] = file:/home/bjerre/.m2/repository/io/quarkus/quarkus-devtools-codestarts/3.0.0.Final/quarkus-devtools-codestarts-3.0.0.Final.jar
[ERROR] urls[84] = file:/home/bjerre/.m2/repository/io/quarkus/qute/qute-core/3.0.0.Final/qute-core-3.0.0.Final.jar
[ERROR] urls[85] = file:/home/bjerre/.m2/repository/io/smallrye/reactive/mutiny/2.1.0/mutiny-2.1.0.jar
[ERROR] urls[86] = file:/home/bjerre/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
[ERROR] urls[87] = file:/home/bjerre/.m2/repository/org/apache/commons/commons-compress/1.23.0/commons-compress-1.23.0.jar
[ERROR] urls[88] = file:/home/bjerre/.m2/repository/io/smallrye/common/smallrye-common-version/2.1.0/smallrye-common-version-2.1.0.jar
[ERROR] urls[89] = file:/home/bjerre/.m2/repository/io/fabric8/maven-model-helper/21/maven-model-helper-21.jar
[ERROR] urls[90] = file:/home/bjerre/.m2/repository/org/jdom/jdom/1.1.3/jdom-1.1.3.jar
[ERROR] urls[91] = file:/home/bjerre/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.14.2/jackson-dataformat-yaml-2.14.2.jar
[ERROR] urls[92] = file:/home/bjerre/.m2/repository/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar
[ERROR] urls[93] = file:/home/bjerre/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.14.2/jackson-datatype-jdk8-2.14.2.jar
[ERROR] urls[94] = file:/home/bjerre/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
[ERROR] urls[95] = file:/home/bjerre/.m2/repository/jakarta/enterprise/jakarta.enterprise.cdi-api/4.0.1/jakarta.enterprise.cdi-api-4.0.1.jar
[ERROR] urls[96] = file:/home/bjerre/.m2/repository/jakarta/enterprise/jakarta.enterprise.lang-model/4.0.1/jakarta.enterprise.lang-model-4.0.1.jar
[ERROR] urls[97] = file:/home/bjerre/.m2/repository/jakarta/el/jakarta.el-api/5.0.1/jakarta.el-api-5.0.1.jar
[ERROR] urls[98] = file:/home/bjerre/.m2/repository/jakarta/interceptor/jakarta.interceptor-api/2.1.0/jakarta.interceptor-api-2.1.0.jar
[ERROR] urls[99] = file:/home/bjerre/.m2/repository/org/freemarker/freemarker/2.3.32/freemarker-2.3.32.jar
[ERROR] urls[100] = file:/home/bjerre/.m2/repository/org/eclipse/parsson/parsson/1.1.1/parsson-1.1.1.jar
[ERROR] urls[101] = file:/home/bjerre/.m2/repository/jakarta/json/jakarta.json-api/2.1.1/jakarta.json-api-2.1.1.jar
[ERROR] urls[102] = file:/home/bjerre/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar
[ERROR] urls[103] = file:/home/bjerre/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.14.2/jackson-annotations-2.14.2.jar
[ERROR] urls[104] = file:/home/bjerre/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar
[ERROR] urls[105] = file:/home/bjerre/.m2/repository/org/twdata/maven/mojo-executor/2.3.1/mojo-executor-2.3.1.jar
[ERROR] urls[106] = file:/home/bjerre/.m2/repository/org/codehaus/plexus/plexus-utils/3.5.1/plexus-utils-3.5.1.jar
[ERROR] urls[107] = file:/home/bjerre/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/2.0.0.Final/slf4j-jboss-logmanager-2.0.0.Final.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

```

**Comment by tomasbjerre** [comment]
Revisiting this after a while.

The original "stuck execution" bug (an infinite/exponential traversal loop for repos with many merge commits) was fixed in 0f5ec29 and released in **1.168.9** (2023-03-12). Current versions (3.x) still contain that fix.

To make sure it holds up on repos with the kind of history described here (hundreds/thousands of merge commits, e.g. @delanym's multi-module case), I generated a synthetic repo with 16,000 commits / 8,000 merge commits across 20 module directories and ran the traversal (with a path filter, from the zero commit to master, like the reproduction steps in this thread). It completed in about 1.2 seconds with correct tag/commit results — no runaway "Work left" growth.

Given that, I believe this is resolved. Closing, but please reopen (ideally with a reproducible repository, as was done for @JohT's case) if you can still trigger a stuck/runaway execution on a current release.
